# Generated by Django 5.1.5 on 2025-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("startDate", models.DateField(auto_now_add=True)),
                ("nbLectures", models.PositiveSmallIntegerField()),
                ("duration", models.DurationField()),
                ("coefficient", models.FloatField()),
                (
                    "courseAvatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_avatars/"
                    ),
                ),
            ],
        ),
    ]
