# Generated by Django 5.1.6 on 2025-02-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
    ]
